//! Windows-specific dynamic library loader (using Win32 APIs).
//!
//! Covered requirements: RF-4, DT-5.

use core::ffi::{c_char, c_int, c_void};
use std::ffi::CStr;
use windows_sys::Win32::Foundation::{FreeLibrary, GetLastError, HMODULE};
use windows_sys::Win32::System::LibraryLoader::{GetProcAddress, LoadLibraryW};

/// Opens the specified dynamic library (converts CStr to UTF-16).
///
/// # Safety
/// The `filename` pointer must point to a valid null-terminated C-string.
pub unsafe fn open(filename: *const c_char) -> *mut c_void {
    let cstr = unsafe { CStr::from_ptr(filename) };
    let string_str = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => return core::ptr::null_mut(),
    };

    // Convert to null-terminated UTF-16 wide string
    let wide: Vec<u16> = string_str.encode_utf16().chain(Some(0)).collect();

    let handle = unsafe { LoadLibraryW(wide.as_ptr()) };
    if handle.is_null() {
        return core::ptr::null_mut();
    }
    handle
}

/// Loads the specified symbol from the library.
///
/// # Safety
/// `handle` must be a valid pointer returned by `open`.
/// `symbol` must point to a valid null-terminated C-string.
pub unsafe fn sym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void {
    if handle.is_null() {
        return core::ptr::null_mut();
    }
    // GetProcAddress returns Option<unsafe extern "system" fn() -> isize> in windows-sys 0.61.
    let addr = unsafe { GetProcAddress(handle as HMODULE, symbol as *const u8) };
    match addr {
        Some(f) => f as *mut c_void,
        None => core::ptr::null_mut(),
    }
}

/// Closes the dynamic library.
///
/// # Safety
/// `handle` must be a valid pointer returned by `open` that has not been closed yet.
pub unsafe fn close(handle: *mut c_void) -> c_int {
    if handle.is_null() {
        return 0;
    }
    let ok = unsafe { FreeLibrary(handle as HMODULE) };
    if ok != 0 {
        0 // Returns 0 for success, matching dlclose behavior
    } else {
        -1 // Failure
    }
}

/// Returns the last error message generated by the loader using GetLastError().
#[derive(Debug, PartialEq, Eq)]
pub enum CudaLoaderError {
    DllNotFound,
    SymbolNotFound,
    ArchitectureMismatch,
    Other(u32),
}

impl std::error::Error for CudaLoaderError {}

impl std::fmt::Display for CudaLoaderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::DllNotFound => write!(f, "DLL not found (ERROR_MOD_NOT_FOUND)"),
            Self::SymbolNotFound => write!(f, "symbol not found (ERROR_PROC_NOT_FOUND)"),
            Self::ArchitectureMismatch => write!(f, "architecture mismatch (ERROR_BAD_EXE_FORMAT)"),
            Self::Other(code) => write!(f, "Windows error code: 0x{code:08X}"),
        }
    }
}

/// Returns the last error message generated by the loader using GetLastError().
pub fn error() -> CudaLoaderError {
    let code = unsafe { GetLastError() };
    match code {
        126 => CudaLoaderError::DllNotFound, // ERROR_MOD_NOT_FOUND
        127 => CudaLoaderError::SymbolNotFound, // ERROR_PROC_NOT_FOUND
        193 => CudaLoaderError::ArchitectureMismatch, // ERROR_BAD_EXE_FORMAT
        _ => CudaLoaderError::Other(code),
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;
    use windows_sys::Win32::Foundation::SetLastError;

    #[test]
    fn test_error_formatting() {
        unsafe { SetLastError(126) };
        assert_eq!(error(), CudaLoaderError::DllNotFound);

        unsafe { SetLastError(127) };
        assert_eq!(error(), CudaLoaderError::SymbolNotFound);

        unsafe { SetLastError(193) };
        assert_eq!(error(), CudaLoaderError::ArchitectureMismatch);

        unsafe { SetLastError(0x00000005) };
        assert_eq!(error(), CudaLoaderError::Other(0x00000005));

        unsafe { SetLastError(0xC0000005) };
        assert_eq!(error(), CudaLoaderError::Other(0xC0000005));

        unsafe { SetLastError(0) };
        assert_eq!(error(), CudaLoaderError::Other(0));
    }
}
