//! Unix-specific dynamic library loader (using `libdl`).
//!
//! Covered requirements: RF-4, DT-5.

use core::ffi::{c_char, c_int, c_void};
use std::ffi::CStr;

#[link(name = "dl")]
unsafe extern "C" {
    fn dlopen(filename: *const c_char, flag: c_int) -> *mut c_void;
    fn dlsym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void;
    fn dlclose(handle: *mut c_void) -> c_int;
    fn dlerror() -> *const c_char;
}

const RTLD_NOW: c_int = 2;

/// Opens the specified dynamic library.
///
/// # Safety
/// The `filename` pointer must point to a valid null-terminated C-string.
pub unsafe fn open(filename: *const c_char) -> *mut c_void {
    unsafe { dlopen(filename, RTLD_NOW) }
}

/// Loads the specified symbol from the library.
///
/// # Safety
/// `handle` must be a valid pointer returned by `open`.
/// `symbol` must point to a valid null-terminated C-string.
pub unsafe fn sym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void {
    unsafe { dlsym(handle, symbol) }
}

/// Closes the dynamic library.
///
/// # Safety
/// `handle` must be a valid pointer returned by `open` that has not been closed yet.
pub unsafe fn close(handle: *mut c_void) -> c_int {
    unsafe { dlclose(handle) }
}

#[derive(Debug, PartialEq, Eq)]
pub enum CudaLoaderError {
    LibraryNotFound(String),
    SymbolMissing(String),
    IncompatibleDriverVersion(String),
    Unknown(String),
}

impl std::fmt::Display for CudaLoaderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::LibraryNotFound(msg) => write!(f, "{msg}"),
            Self::SymbolMissing(msg) => write!(f, "{msg}"),
            Self::IncompatibleDriverVersion(msg) => write!(f, "{msg}"),
            Self::Unknown(msg) => write!(f, "{msg}"),
        }
    }
}

impl std::error::Error for CudaLoaderError {}

impl CudaLoaderError {
    /// Helper to bridge to std::io::Error conceptually.
    pub fn into_io_error(self) -> std::io::Error {
        let kind = match &self {
            Self::LibraryNotFound(_) => std::io::ErrorKind::NotFound,
            Self::SymbolMissing(_) => std::io::ErrorKind::NotFound,
            Self::IncompatibleDriverVersion(_) => std::io::ErrorKind::InvalidInput,
            Self::Unknown(_) => std::io::ErrorKind::Other,
        };
        std::io::Error::new(kind, self.to_string())
    }
}

/// Returns the last error message generated by the loader.
pub fn error() -> CudaLoaderError {
    let err = unsafe { dlerror() };
    if err.is_null() {
        return CudaLoaderError::Unknown("unknown dlopen error".to_string());
    }

    // SAFETY: err is guaranteed by the system to be a valid static C-string.
    let msg = unsafe { CStr::from_ptr(err) }
        .to_string_lossy()
        .into_owned();

    if msg.contains("cannot open shared object file") || msg.contains("No such file or directory") {
        CudaLoaderError::LibraryNotFound(msg)
    } else if msg.contains("undefined symbol") {
        CudaLoaderError::SymbolMissing(msg)
    } else if msg.contains("wrong ELF class")
        || msg.contains("invalid ELF header")
        || msg.contains("incompatible")
    {
        CudaLoaderError::IncompatibleDriverVersion(msg)
    } else {
        CudaLoaderError::Unknown(msg)
    }
}
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error_formatting() {
        // Clear any preexisting errors
        let _ = error();

        let bogus_lib = c"this_library_does_not_exist_12345.so";
        let handle = unsafe { open(bogus_lib.as_ptr()) };
        assert!(
            handle.is_null(),
            "Opening a non-existent library should fail"
        );

        // The first call to error() should return the dlerror message
        let err = error();
        let err_msg = err.to_string();
        assert!(!err_msg.is_empty());
        assert_ne!(err_msg, "unknown dlopen error");
        assert!(
            err_msg.contains("this_library_does_not_exist_12345.so"),
            "Error message should mention the failing library, got: {}",
            err_msg
        );
        assert!(matches!(err, CudaLoaderError::LibraryNotFound(_)));

        // The second call to error() should return the fallback string because dlerror clears the error
        let err2 = error();
        assert_eq!(err2.to_string(), "unknown dlopen error");
        assert!(matches!(err2, CudaLoaderError::Unknown(_)));
    }
}
