//! Windows-specific dynamic library loader (using Win32 APIs).
//!
//! Covered requirements: RF-4, DT-5.

use core::ffi::{c_char, c_int, c_void};
use std::ffi::CStr;
use windows_sys::Win32::Foundation::{FreeLibrary, GetLastError, HMODULE};
use windows_sys::Win32::System::LibraryLoader::{GetProcAddress, LoadLibraryW};

/// Opens the specified dynamic library (converts CStr to UTF-16).
///
/// # Safety
/// The `filename` pointer must point to a valid null-terminated C-string.
pub unsafe fn open(filename: *const c_char) -> *mut c_void {
    let cstr = unsafe { CStr::from_ptr(filename) };
    let string_str = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => return core::ptr::null_mut(),
    };

    // Convert to null-terminated UTF-16 wide string
    let wide: Vec<u16> = string_str.encode_utf16().chain(Some(0)).collect();

    let handle = unsafe { LoadLibraryW(wide.as_ptr()) };
    if handle.is_null() {
        return core::ptr::null_mut();
    }
    handle as *mut c_void
}

/// Loads the specified symbol from the library.
///
/// # Safety
/// `handle` must be a valid pointer returned by `open`.
/// `symbol` must point to a valid null-terminated C-string.
pub unsafe fn sym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void {
    if handle.is_null() {
        return core::ptr::null_mut();
    }
    // GetProcAddress returns Option<unsafe extern "system" fn() -> isize> in windows-sys 0.61.
    let addr = unsafe { GetProcAddress(handle as HMODULE, symbol as *const u8) };
    match addr {
        Some(f) => f as *mut c_void,
        None => core::ptr::null_mut(),
    }
}

/// Closes the dynamic library.
///
/// # Safety
/// `handle` must be a valid pointer returned by `open` that has not been closed yet.
pub unsafe fn close(handle: *mut c_void) -> c_int {
    if handle.is_null() {
        return 0;
    }
    let ok = unsafe { FreeLibrary(handle as HMODULE) };
    if ok != 0 {
        0 // Returns 0 for success, matching dlclose behavior
    } else {
        -1 // Failure
    }
}

/// Returns the last error message generated by the loader using GetLastError().
pub fn error() -> String {
    let code = unsafe { GetLastError() };
    format!("Windows error code: 0x{code:08X}")
}
