//! Unix-specific dynamic library loader (using `libdl`).
//!
//! Covered requirements: RF-4, DT-5.

use core::ffi::{c_char, c_int, c_void};
use std::ffi::CStr;

#[link(name = "dl")]
unsafe extern "C" {
    fn dlopen(filename: *const c_char, flag: c_int) -> *mut c_void;
    fn dlsym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void;
    fn dlclose(handle: *mut c_void) -> c_int;
    fn dlerror() -> *const c_char;
}

const RTLD_NOW: c_int = 2;

/// Opens the specified dynamic library.
///
/// # Safety
/// The `filename` pointer must point to a valid null-terminated C-string.
pub unsafe fn open(filename: *const c_char) -> *mut c_void {
    unsafe { dlopen(filename, RTLD_NOW) }
}

/// Loads the specified symbol from the library.
///
/// # Safety
/// `handle` must be a valid pointer returned by `open`.
/// `symbol` must point to a valid null-terminated C-string.
pub unsafe fn sym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void {
    unsafe { dlsym(handle, symbol) }
}

/// Closes the dynamic library.
///
/// # Safety
/// `handle` must be a valid pointer returned by `open` that has not been closed yet.
pub unsafe fn close(handle: *mut c_void) -> c_int {
    unsafe { dlclose(handle) }
}

/// Returns the last error message generated by the loader.
pub fn error() -> String {
    let err = unsafe { dlerror() };
    if err.is_null() {
        "unknown dlopen error".to_string()
    } else {
        // SAFETY: err is guaranteed by the system to be a valid static C-string.
        unsafe { CStr::from_ptr(err) }
            .to_string_lossy()
            .into_owned()
    }
}
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error_formatting() {
        // Clear any preexisting errors
        let _ = error();

        let bogus_lib = c"this_library_does_not_exist_12345.so";
        let handle = unsafe { open(bogus_lib.as_ptr()) };
        assert!(
            handle.is_null(),
            "Opening a non-existent library should fail"
        );

        // The first call to error() should return the dlerror message
        let err_msg = error();
        assert!(!err_msg.is_empty());
        assert_ne!(err_msg, "unknown dlopen error");
        assert!(
            err_msg.contains("this_library_does_not_exist_12345.so"),
            "Error message should mention the failing library, got: {}",
            err_msg
        );

        // The second call to error() should return the fallback string because dlerror clears the error
        let err_msg2 = error();
        assert_eq!(err_msg2, "unknown dlopen error");
    }

    /// `sym` and `close` are thin `dlsym`/`dlclose` wrappers. Exercise them
    /// against a library every Unix host has, so the wrappers are covered
    /// without depending on an NVIDIA driver install.
    #[test]
    fn test_sym_and_close_roundtrip_on_libc() {
        let handle = unsafe { open(c"libc.so.6".as_ptr()) };
        assert!(!handle.is_null(), "libc.so.6 must be loadable: {}", error());

        let strlen = unsafe { sym(handle, c"strlen".as_ptr()) };
        assert!(!strlen.is_null(), "libc must export strlen: {}", error());

        // A missing symbol resolves to null and leaves the handle usable.
        let missing = unsafe { sym(handle, c"ramshared_no_such_symbol".as_ptr()) };
        assert!(missing.is_null());

        let rc = unsafe { close(handle) };
        assert_eq!(rc, 0, "dlclose of a real handle must succeed");
    }
}
