/* SPDX-License-Identifier: MIT */
#pragma once

#include <ntddk.h>
#include "protocol.h"

#ifndef FILE_DEVICE_MASS_STORAGE
#define FILE_DEVICE_MASS_STORAGE 0x0000002d
#endif

#define IOCTL_RAMSHARED_REGISTER_QUEUE \
	CTL_CODE(FILE_DEVICE_MASS_STORAGE, 0x800 | RAMSHARED_IOCTL_FN_REGISTER_QUEUE, \
		 METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RAMSHARED_UNREGISTER_QUEUE \
	CTL_CODE(FILE_DEVICE_MASS_STORAGE, 0x800 | RAMSHARED_IOCTL_FN_UNREGISTER_QUEUE, \
		 METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RAMSHARED_COMMIT_AND_FETCH \
	CTL_CODE(FILE_DEVICE_MASS_STORAGE, 0x800 | RAMSHARED_IOCTL_FN_COMMIT_AND_FETCH, \
		 METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RAMSHARED_CREATE_DISK \
	CTL_CODE(FILE_DEVICE_MASS_STORAGE, 0x800 | RAMSHARED_IOCTL_FN_CREATE_DISK, \
		 METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RAMSHARED_DESTROY_DISK \
	CTL_CODE(FILE_DEVICE_MASS_STORAGE, 0x800 | RAMSHARED_IOCTL_FN_DESTROY_DISK, \
		 METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

NTSTATUS
CtlCreateControlDevice(
	_In_ PDRIVER_OBJECT DriverObject,
	_In_ PCWSTR Sddl,
	_In_ const GUID *InterfaceGuid);

VOID CtlDeleteControlDevice(VOID);

/*
 * Install dispatch hooks: save StorPort originals, wrap for control device
 * only (DT-25). Call AFTER StorPortInitialize.
 */
NTSTATUS
CtlInstallDispatchHooks(_In_ PDRIVER_OBJECT DriverObject);

PDEVICE_OBJECT CtlGetControlDevice(VOID);
