[package]
name = "ramshared-config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "1.1"
serde_path_to_error = "0.1"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

[dev-dependencies]
tempfile = "3.27.0"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Security_Authorization", "Win32_Security", "Win32_System_Memory"] }
